kind: Service
apiVersion: v1
metadata:
  name: endpoint-service
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: endpoint-service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
       - port: 9376
