kind: Secret
apiVersion: v1
metadata:
  name: mongo-secret
type: Opaque
data:
 username: dXNlcm5hbWU=
 password: cGFzc3dvcmQ=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo-configmap
data:
  mongourl: mongo-service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
   replicas: 1
   selector:
     matchLabels:
        app: mongo
   template:
     metadata:
      labels:
        app: mongo
     spec:
       containers:
            - name: mongo
              image: mongo
              ports:
                 - containerPort: 27017 
              env:
                - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                  valueFrom:
                     secretKeyRef: 
                           name: mongo-secret
                           key: username
                 

                - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                  valueFrom:
                     secretKeyRef:
                            name: mongo-secret
                            key: password
---
kind: Service
apiVersion: v1
metadata:
   name: mongo-service
spec:
  selector:
     app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: mongo-express
    labels:
      app: mongo-express
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mongo-express
  template:
    metadata:
     labels:
       app: mongo-express
    spec:
      containers:
         - name: mongo-express
           image: mongo-express
           ports:
             - containerPort: 8080
           env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                   name: mongo-configmap
                   key: mongourl
---
kind: Service
apiVersion: v1
metadata:
   name: mongo-express-service
spec:
  selector:
     app: mongo-express
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30000
