kind: Secret
apiVersion: v1
metadata:
   name: mysecret
type: Opaque
immutable: true
data:
 username: cGFzc3dvcmQ=
 password: cGFzc3dvcmQ=
---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
     - name: mypod
       image: nginx:perl
       volumeMounts:
          - name: myvolume
            mountPath: "/etc/myvolume"
  volumes:
    - name: myvolume
      secret:
         secretName: mysecret
         items:
           - key: username
             path: volume
