
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    release: "stable"
spec:
  capacity:
    storage: 2Gi
  accessModes:
     - ReadWriteOnce
  hostPath:
     path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
    storage: 1Gi
  selector:
   matchLabels:
      release: "stable"
---
apiVersion: v1
kind: Pod
metadata:
   name: mypod1
spec:
  containers:
      - name: mypod1
        image: nginx:perl
        volumeMounts:
          - name: myvolume
            mountPath: /data
  volumes:
     - name: myvolume
       persistentVolumeClaim:
            claimName: example-pvc  
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
    - name: mypod1
      image: nginx:perl
      volumeMounts:
            - name: myvolume
              mountPath: /data          
  volumes:
     - name: myvolume
       persistentVolumeClaim:
         claimName: example-pvc        
